# syntax=docker/dockerfile:1

# ============================================================
# CITADEL SERVER — Multi-stage Docker build
#
# Prerequisites:
#   1. Generate SQLx offline metadata BEFORE building:
#      cargo install sqlx-cli --no-default-features --features postgres,rustls
#      export DATABASE_URL=postgres://citadel:citadel@localhost:5432/citadel
#      cargo sqlx prepare
#
#   2. Build:
#      docker build -t citadel-server .
#
#   3. Run with docker-compose:
#      docker compose up
# ============================================================

# ── Stage 1: Build ───────────────────────────────────────────
FROM rust:1.93-slim AS builder

WORKDIR /app

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
     ca-certificates pkg-config libssl-dev \
  && rm -rf /var/lib/apt/lists/*

# Copy manifests first (better layer caching)
COPY Cargo.toml Cargo.lock* ./

# Copy SQLx offline metadata (generated by: cargo sqlx prepare)
COPY .sqlx ./.sqlx

# Copy source and migrations
COPY src ./src
COPY migrations ./migrations

# Use offline SQLx metadata (no live DB connection needed at build time)
ENV SQLX_OFFLINE=true

RUN cargo build --release

# ── Stage 2: Runtime ─────────────────────────────────────────
FROM debian:bookworm-slim

RUN apt-get update \
  && apt-get install -y --no-install-recommends ca-certificates \
  && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/release/citadel-server /usr/local/bin/citadel-server

EXPOSE 3000

CMD ["citadel-server"]
