#!/bin/bash
set -euo pipefail

# ═══════════════════════════════════════════════════════════
# Discreet — Production Secret Generator
# Run ONCE on your production server to generate .env
# NEVER commit the output. NEVER share these values.
# ═══════════════════════════════════════════════════════════

echo "═══════════════════════════════════════════════════════"
echo " Discreet — Generating Production Secrets"
echo "═══════════════════════════════════════════════════════"
echo ""

# Generate cryptographically secure random values
DB_PASSWORD=$(openssl rand -hex 24)
REDIS_PASSWORD=$(openssl rand -hex 24)
JWT_SECRET=$(openssl rand -hex 64)
AGENT_KEY_SECRET=$(openssl rand -hex 32)
TOTP_ENCRYPTION_KEY=$(openssl rand -hex 32)
TURN_SECRET=$(openssl rand -hex 32)

# Prompt for domain and Resend key
read -p "Enter your domain (e.g., discreetai.net): " DOMAIN
read -p "Enter Resend API key (or press Enter to skip): " RESEND_KEY

cat > .env << EOF
# ═══════════════════════════════════════════════════════════
# Discreet — Production Environment Configuration
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# WARNING: This file contains secrets. Never commit to git.
# ═══════════════════════════════════════════════════════════

# ── Required ──
DATABASE_URL=postgres://discreet:${DB_PASSWORD}@localhost:5432/discreet
REDIS_URL=redis://:${REDIS_PASSWORD}@127.0.0.1:6379
JWT_SECRET=${JWT_SECRET}

# ── Encryption ──
TOTP_ENCRYPTION_KEY=${TOTP_ENCRYPTION_KEY}
AGENT_KEY_SECRET=${AGENT_KEY_SECRET}

# ── Email (Resend HTTP API) ──
RESEND_API_KEY=${RESEND_KEY:-CONFIGURE_AFTER_DOMAIN_VERIFICATION}
SMTP_FROM=noreply@${DOMAIN}

# ── URLs ──
PUBLIC_URL=https://${DOMAIN}
APP_URL=https://${DOMAIN}
API_URL=https://api.${DOMAIN}
ALLOWED_ORIGINS=https://${DOMAIN}

# ── Production mode ──
RUST_ENV=production
HOST=0.0.0.0
PORT=3000
RUST_LOG=discreet_server=info,tower_http=info

# ── TURN Server (voice/video NAT traversal) ──
TURN_SECRET=${TURN_SECRET}
TURN_REALM=turn.${DOMAIN}
TURN_HOST=turn.${DOMAIN}

# ── Cloudflare Turnstile (anonymous registration CAPTCHA) ──
TURNSTILE_SECRET_KEY=CONFIGURE_IN_CLOUDFLARE_DASHBOARD
EOF

# Generate matching docker-compose override
cat > docker-compose.override.yml << EOF
# Production overrides — generated by generate-secrets.sh
# This file is .gitignored and contains real credentials.
services:
  postgres:
    environment:
      POSTGRES_USER: discreet
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: discreet
  redis:
    command: redis-server --requirepass ${REDIS_PASSWORD}
EOF

chmod 600 .env
chmod 600 docker-compose.override.yml

echo ""
echo "═══════════════════════════════════════════════════════"
echo " ✅ Secrets generated successfully!"
echo ""
echo " Files created:"
echo "   .env                       (application config)"
echo "   docker-compose.override.yml (database credentials)"
echo ""
echo " Both files have 600 permissions (owner read/write only)"
echo ""
echo " NEXT STEPS:"
echo "   1. Review .env"
echo "   2. docker compose up -d"
echo "   3. Apply migrations:"
echo "      for f in migrations/*.sql; do"
echo "        cat \"\$f\" | docker compose exec -T postgres psql -U discreet -d discreet"
echo "      done"
echo "   4. cargo build --release"
echo "   5. sudo cp docs/discreet.service /etc/systemd/system/"
echo "   6. sudo systemctl enable --now discreet"
echo ""
echo " Binary: ./target/release/discreet-server"
echo ""
echo " BACKUP .env SECURELY. If you lose it, you lose access"
echo " to encrypted data (agent keys, TOTP secrets)."
echo "═══════════════════════════════════════════════════════"
