#!/bin/bash
# ═══════════════════════════════════════════════════════════
# Discreet — Production Secret Generator
# Run this ONCE on your production server to generate .env
# NEVER commit the output. NEVER share these values.
# ═══════════════════════════════════════════════════════════

set -euo pipefail

echo "═══════════════════════════════════════════════════════"
echo " Discreet — Generating Production Secrets"
echo "═══════════════════════════════════════════════════════"
echo ""

# Generate cryptographically secure random values
DB_PASSWORD=$(openssl rand -hex 24)
JWT_SECRET=$(openssl rand -hex 64)
AGENT_KEY_SECRET=$(openssl rand -hex 32)
TOTP_ENCRYPTION_KEY=$(openssl rand -hex 32)
REDIS_PASSWORD=$(openssl rand -hex 24)

# Prompt for domain
read -p "Enter your domain (e.g., discreetai.net): " DOMAIN
read -p "Enter Resend API key (or press Enter to skip): " RESEND_KEY

cat > .env << EOF
# ═══════════════════════════════════════════════════════════
# Discreet — Production Environment Configuration
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# WARNING: This file contains secrets. Never commit to git.
# ═══════════════════════════════════════════════════════════

# ── Database ──
# Credentials were randomly generated. Change docker-compose.yml to match.
DATABASE_URL=postgres://discreet:${DB_PASSWORD}@localhost:5432/discreet

# ── Redis ──
REDIS_URL=redis://:${REDIS_PASSWORD}@127.0.0.1:6379

# ── Authentication ──
# 128-character hex string for JWT signing. Unique to this deployment.
JWT_SECRET=${JWT_SECRET}

# ── CORS ──
# CRITICAL: Must be your exact domain. Never use * in production.
CORS_ORIGINS=https://${DOMAIN}

# ── AI Agent Encryption ──
# Encrypts AI provider API keys at rest in the database.
AGENT_KEY_SECRET=${AGENT_KEY_SECRET}

# ── TOTP Encryption ──
# Encrypts 2FA TOTP secrets at rest in the database.
TOTP_ENCRYPTION_KEY=${TOTP_ENCRYPTION_KEY}

# ── Email (Resend) ──
RESEND_API_KEY=${RESEND_KEY:-CONFIGURE_AFTER_DOMAIN_VERIFICATION}

# ── Optional: Twilio (Phone Verification) ──
# TWILIO_ACCOUNT_SID=
# TWILIO_AUTH_TOKEN=
# TWILIO_PHONE_NUMBER=

# ── Optional: AI Provider ──
# AGENT_ANTHROPIC_API_KEY=
# AGENT_OLLAMA_BASE_URL=http://localhost:11434
EOF

# Generate matching docker-compose override
cat > docker-compose.override.yml << EOF
# Production overrides — generated by generate-secrets.sh
# This file is .gitignored and contains real credentials.
services:
  postgres:
    environment:
      POSTGRES_USER: discreet
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: discreet
  redis:
    command: redis-server --requirepass ${REDIS_PASSWORD}
EOF

chmod 600 .env
chmod 600 docker-compose.override.yml

echo ""
echo "═══════════════════════════════════════════════════════"
echo " ✅ Secrets generated successfully!"
echo ""
echo " Files created:"
echo "   .env                       (application config)"
echo "   docker-compose.override.yml (database credentials)"
echo ""
echo " Both files have 600 permissions (owner read/write only)"
echo ""
echo " NEXT STEPS:"
echo "   1. Review .env and docker-compose.override.yml"
echo "   2. Run: docker compose down && docker compose up -d"
echo "   3. Re-apply migrations with new credentials:"
echo "      PGPASSWORD=${DB_PASSWORD} psql -h localhost -U discreet -d discreet"
echo "   4. Build and start: cargo build --release"
echo "   5. sudo systemctl restart discreet"
echo ""
echo " BACKUP THIS FILE SECURELY. If you lose .env, you lose"
echo " access to encrypted data (agent keys, TOTP secrets)."
echo "═══════════════════════════════════════════════════════"
