# ─────────────────────────────────────────────────────────────
# Discreet — Single-command deployment script for Windows
# Run: powershell -ExecutionPolicy Bypass -File scripts\setup.ps1
# ─────────────────────────────────────────────────────────────
$ErrorActionPreference = "Stop"

$VERSION = "1.0.0"

# ── Banner ──────────────────────────────────────────────────
Write-Host ""
Write-Host "╔══════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║  Discreet — Encrypted Communication Platform        ║" -ForegroundColor Cyan
Write-Host "║  Version: $VERSION                                      ║" -ForegroundColor Cyan
Write-Host "╚══════════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

# ── Check required tools ───────────────────────────────────
Write-Host "[1/8] Checking required tools..." -ForegroundColor Yellow
$missing = 0

# Docker or Podman
$containerCmd = $null
if (Get-Command docker -ErrorAction SilentlyContinue) {
    $containerCmd = "docker"
    $dockerVer = docker --version 2>$null
    Write-Host "  ✓ docker $dockerVer" -ForegroundColor Green
} elseif (Get-Command podman -ErrorAction SilentlyContinue) {
    $containerCmd = "podman"
    $podmanVer = podman --version 2>$null
    Write-Host "  ✓ podman $podmanVer" -ForegroundColor Green
} else {
    Write-Host "  ✗ docker/podman — not found. Install with:" -ForegroundColor Red
    Write-Host "    winget install Docker.DockerDesktop" -ForegroundColor Gray
    $missing++
}

# Node v20+
if (Get-Command node -ErrorAction SilentlyContinue) {
    $nodeVer = (node -v) -replace '^v', ''
    $nodeMajor = [int]($nodeVer.Split('.')[0])
    if ($nodeMajor -ge 20) {
        Write-Host "  ✓ node v$nodeVer" -ForegroundColor Green
    } else {
        Write-Host "  ✗ node v$nodeVer — v20+ required. Install with:" -ForegroundColor Red
        Write-Host "    winget install OpenJS.NodeJS.LTS" -ForegroundColor Gray
        $missing++
    }
} else {
    Write-Host "  ✗ node — not found. Install with:" -ForegroundColor Red
    Write-Host "    winget install OpenJS.NodeJS.LTS" -ForegroundColor Gray
    $missing++
}

# Cargo
if (Get-Command cargo -ErrorAction SilentlyContinue) {
    $cargoVer = cargo --version 2>$null
    Write-Host "  ✓ cargo $cargoVer" -ForegroundColor Green
} else {
    Write-Host "  ✗ cargo — not found. Install with:" -ForegroundColor Red
    Write-Host "    winget install Rustlang.Rustup" -ForegroundColor Gray
    $missing++
}

# Git
if (Get-Command git -ErrorAction SilentlyContinue) {
    $gitVer = git --version 2>$null
    Write-Host "  ✓ $gitVer" -ForegroundColor Green
} else {
    Write-Host "  ✗ git — not found. Install with:" -ForegroundColor Red
    Write-Host "    winget install Git.Git" -ForegroundColor Gray
    $missing++
}

# OpenSSL
if (Get-Command openssl -ErrorAction SilentlyContinue) {
    $sslVer = openssl version 2>$null
    Write-Host "  ✓ openssl $sslVer" -ForegroundColor Green
} else {
    Write-Host "  ✗ openssl — not found. Install with:" -ForegroundColor Red
    Write-Host "    winget install ShiningLight.OpenSSL" -ForegroundColor Gray
    $missing++
}

if ($missing -gt 0) {
    Write-Host ""
    Write-Host "ERROR: Missing required tools. Install them and re-run this script." -ForegroundColor Red
    exit 1
}
Write-Host ""

# ── Generate secrets ───────────────────────────────────────
Write-Host "[2/8] Generating secrets..." -ForegroundColor Yellow
$dbPassword    = openssl rand -hex 24
$jwtSecret     = openssl rand -hex 64
$agentKey      = openssl rand -hex 32
$totpKey       = openssl rand -hex 32
$redisPassword = openssl rand -hex 24
Write-Host "  ✓ All secrets generated (DB, JWT, Agent, TOTP, Redis)" -ForegroundColor Green
Write-Host ""

# ── Write .env ─────────────────────────────────────────────
Write-Host "[3/8] Writing .env..." -ForegroundColor Yellow
$envContent = @"
# ─── Generated by scripts/setup.ps1 ──────────────────────
# Database
DATABASE_URL=postgres://discreet:${dbPassword}@localhost:5432/discreet

# Redis
REDIS_URL=redis://:${redisPassword}@127.0.0.1:6379

# JWT signing key (128 hex chars)
JWT_SECRET=${jwtSecret}

# Master secret for encrypting agent API keys at rest
AGENT_KEY_SECRET=${agentKey}

# AES-256-GCM key for TOTP secret encryption
TOTP_ENCRYPTION_KEY=${totpKey}

# Allowed CORS origins
CORS_ORIGINS=http://localhost:3000
"@
Set-Content -Path ".env" -Value $envContent -Encoding UTF8
# Restrict .env to current user only
$acl = Get-Acl ".env"
$acl.SetAccessRuleProtection($true, $false)
$rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
    [System.Security.Principal.WindowsIdentity]::GetCurrent().Name,
    "FullControl", "Allow")
$acl.AddAccessRule($rule)
Set-Acl ".env" $acl
Write-Host "  ✓ .env written (restricted permissions)" -ForegroundColor Green
Write-Host ""

# ── Write docker-compose.override.yml ──────────────────────
Write-Host "[4/8] Writing docker-compose.override.yml..." -ForegroundColor Yellow
$overrideContent = @"
# ─── Generated by scripts/setup.ps1 ──────────────────────
# Overrides default docker-compose.yml with secure passwords
# and localhost-only bindings.
services:
  postgres:
    environment:
      POSTGRES_USER: discreet
      POSTGRES_PASSWORD: "${dbPassword}"
      POSTGRES_DB: discreet
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    command: redis-server --requirepass "${redisPassword}"
    ports:
      - "127.0.0.1:6379:6379"
"@
Set-Content -Path "docker-compose.override.yml" -Value $overrideContent -Encoding UTF8
$acl2 = Get-Acl "docker-compose.override.yml"
$acl2.SetAccessRuleProtection($true, $false)
$rule2 = New-Object System.Security.AccessControl.FileSystemAccessRule(
    [System.Security.Principal.WindowsIdentity]::GetCurrent().Name,
    "FullControl", "Allow")
$acl2.AddAccessRule($rule2)
Set-Acl "docker-compose.override.yml" $acl2
Write-Host "  ✓ docker-compose.override.yml written (restricted permissions)" -ForegroundColor Green
Write-Host ""

# ── Start containers ───────────────────────────────────────
Write-Host "[5/8] Starting PostgreSQL and Redis..." -ForegroundColor Yellow
if ($containerCmd -eq "podman") {
    podman compose up -d
} else {
    docker compose up -d
}
Write-Host ""

# ── Wait for PostgreSQL ────────────────────────────────────
Write-Host "[6/8] Waiting for PostgreSQL to be ready..." -ForegroundColor Yellow
$waited = 0
$maxWait = 30
while ($waited -lt $maxWait) {
    $result = docker compose exec -T postgres pg_isready -U discreet 2>$null
    if ($LASTEXITCODE -eq 0) { break }
    Write-Host "." -NoNewline
    Start-Sleep -Seconds 1
    $waited++
}
if ($waited -ge $maxWait) {
    Write-Host ""
    Write-Host "ERROR: PostgreSQL did not become ready within ${maxWait}s." -ForegroundColor Red
    Write-Host "Check logs with: docker compose logs postgres"
    exit 1
}
Write-Host " ready! (${waited}s)" -ForegroundColor Green
Write-Host ""

# ── Apply migrations ──────────────────────────────────────
Write-Host "[7/8] Applying database migrations..." -ForegroundColor Yellow
$migrationCount = 0
Get-ChildItem -Path "migrations\*.sql" | Sort-Object Name | ForEach-Object {
    $env:PGPASSWORD = $dbPassword
    Get-Content $_.FullName | docker compose exec -T postgres psql -U discreet -d discreet -q 2>$null
    $migrationCount++
}
Write-Host "  ✓ Applied $migrationCount migrations" -ForegroundColor Green
Write-Host ""

# ── Build client & server ─────────────────────────────────
Write-Host "[8/8] Building..." -ForegroundColor Yellow

Write-Host "  → Installing client dependencies..."
Push-Location client-next
npm ci --silent
Write-Host "  → Building client..."
npm run build
Pop-Location

Write-Host ""
Write-Host "  → Building Rust server (release mode)..."
Write-Host "    ⚠  This takes 15–20 minutes on first build." -ForegroundColor DarkYellow
cargo build --release

Write-Host ""
Write-Host "╔══════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "║  ✓ Discreet is ready at http://localhost:3000       ║" -ForegroundColor Green
Write-Host "╚══════════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""
Write-Host "To start the server:"
Write-Host "  .\target\release\citadel-server.exe"
Write-Host ""
Write-Host "To stop the databases:"
Write-Host "  docker compose down"
Write-Host ""
Write-Host "Your secrets are in .env (restricted permissions). Back it up securely."
Write-Host ""
