# ===========================================================
# Discreet -- Local Development Setup (Windows PowerShell)
# Run: powershell -ExecutionPolicy Bypass -File scripts\setup.ps1
# ===========================================================

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "===========================================================" -ForegroundColor Cyan
Write-Host " Discreet -- Local Development Setup" -ForegroundColor Cyan
Write-Host "===========================================================" -ForegroundColor Cyan
Write-Host ""

# -- Step 1: Check prerequisites -----------------------------------------------

Write-Host "Step 1: Checking prerequisites" -ForegroundColor Yellow

function Test-Command($name, $hint) {
    if (Get-Command $name -ErrorAction SilentlyContinue) {
        Write-Host "  + $name" -ForegroundColor Green
    } else {
        Write-Host "  x $name not found. $hint" -ForegroundColor Red
        exit 1
    }
}

Test-Command "docker" "Install Docker Desktop: https://docs.docker.com/desktop/install/windows/"
Test-Command "cargo" "Install Rust: https://rustup.rs"
Test-Command "node" "Install Node.js 20+: https://nodejs.org"
Test-Command "git" "Install Git: https://git-scm.com"
Test-Command "openssl" 'Install via Git for Windows or choco install openssl'

$nodeMajor = [int]((node -v) -replace 'v(\d+)\..*', '$1')
if ($nodeMajor -lt 20) {
    Write-Host "  x Node.js $nodeMajor found, need 20+" -ForegroundColor Red
    exit 1
}
Write-Host ""

# -- Step 2: Generate secrets --------------------------------------------------

Write-Host "Step 2: Generating secrets" -ForegroundColor Yellow
$DB_PASSWORD = (openssl rand -hex 16).Trim()
$REDIS_PASSWORD = (openssl rand -hex 16).Trim()
$JWT_SECRET = (openssl rand -hex 64).Trim()
$AGENT_KEY = (openssl rand -hex 32).Trim()
$TOTP_KEY = (openssl rand -hex 32).Trim()
Write-Host "  + Secrets generated" -ForegroundColor Green
Write-Host ""

# -- Step 3: Write .env --------------------------------------------------------

Write-Host "Step 3: Writing .env" -ForegroundColor Yellow
$timestamp = (Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")
$envContent = @"
# Generated by scripts/setup.ps1 on $timestamp
# Local development -- not for production use.

# -- Required --
DATABASE_URL=postgres://discreet:${DB_PASSWORD}@localhost:5432/discreet
REDIS_URL=redis://:${REDIS_PASSWORD}@127.0.0.1:6379
JWT_SECRET=$JWT_SECRET

# -- Encryption --
TOTP_ENCRYPTION_KEY=$TOTP_KEY
AGENT_KEY_SECRET=$AGENT_KEY

# -- Dev mode (skips production credential checks) --
SELF_HOSTED=true

# -- CORS (Vite dev server + backend) --
CORS_ORIGINS=http://localhost:5173,http://localhost:3000

# -- Server --
HOST=0.0.0.0
PORT=3000
RUST_LOG=discreet_server=debug,tower_http=debug
"@
Set-Content -Path ".env" -Value $envContent -Encoding UTF8
Write-Host "  + .env written" -ForegroundColor Green
Write-Host ""

# -- Step 4: Write docker-compose.override.yml ---------------------------------

Write-Host "Step 4: Writing docker-compose.override.yml" -ForegroundColor Yellow
$overrideContent = @"
# Generated by scripts/setup.ps1 -- contains credentials.
services:
  postgres:
    environment:
      POSTGRES_USER: discreet
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: discreet
  redis:
    command: redis-server --requirepass $REDIS_PASSWORD
"@
Set-Content -Path "docker-compose.override.yml" -Value $overrideContent -Encoding UTF8
Write-Host "  + docker-compose.override.yml written" -ForegroundColor Green
Write-Host ""

# -- Step 5: Set permissions (Windows ACL) -------------------------------------

Write-Host "Step 5: Setting file permissions" -ForegroundColor Yellow
$currentUser = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
foreach ($file in @(".env", "docker-compose.override.yml")) {
    if (Test-Path $file) {
        try {
            $acl = Get-Acl $file
            $acl.SetAccessRuleProtection($true, $false)
            $rule = New-Object System.Security.AccessControl.FileSystemAccessRule($currentUser, "FullControl", "Allow")
            $acl.SetAccessRule($rule)
            Set-Acl -Path $file -AclObject $acl
        } catch {
            Write-Host "  ! Could not restrict permissions on $file" -ForegroundColor Yellow
        }
    }
}
Write-Host "  + Permissions set" -ForegroundColor Green
Write-Host ""

# -- Step 6: Start Docker containers ------------------------------------------

Write-Host "Step 6: Starting PostgreSQL and Redis" -ForegroundColor Yellow
docker compose up -d
Write-Host "  + Containers started" -ForegroundColor Green
Write-Host ""

# -- Step 7: Wait for PostgreSQL -----------------------------------------------

Write-Host "Step 7: Waiting for PostgreSQL" -ForegroundColor Yellow
$attempts = 0
do {
    $attempts++
    if ($attempts -ge 30) {
        Write-Host "  x PostgreSQL not ready after 30s" -ForegroundColor Red
        exit 1
    }
    Start-Sleep -Seconds 1
    Write-Host -NoNewline "."
    docker compose exec -T postgres pg_isready -U discreet -d discreet 2>$null | Out-Null
} while ($LASTEXITCODE -ne 0)
Write-Host ""
Write-Host "  + PostgreSQL ready" -ForegroundColor Green
Write-Host ""

# -- Step 8: Apply migrations --------------------------------------------------

Write-Host "Step 8: Applying migrations" -ForegroundColor Yellow
$prevPref = $ErrorActionPreference
$ErrorActionPreference = "Continue"
Get-ChildItem migrations\*.sql | Sort-Object Name | ForEach-Object {
    Get-Content $_.FullName | docker compose exec -T postgres psql -U discreet -d discreet -q 2>$null
}
$ErrorActionPreference = $prevPref
Write-Host "  + Migrations applied" -ForegroundColor Green
Write-Host ""

# -- Step 9: Install frontend dependencies -------------------------------------

Write-Host "Step 9: Installing frontend dependencies" -ForegroundColor Yellow
Push-Location client
npm ci --silent
Pop-Location
Write-Host "  + Frontend ready" -ForegroundColor Green
Write-Host ""

# -- Step 10: Done -------------------------------------------------------------

Write-Host ""
Write-Host "===========================================================" -ForegroundColor Cyan
Write-Host " Setup complete!" -ForegroundColor Green
Write-Host ""
Write-Host "  Start backend:   cargo run"
Write-Host "  Start frontend:  cd client; npm run dev"
Write-Host "  Open browser:    http://localhost:5173"
Write-Host ""
Write-Host "  Health check:    http://localhost:3000/health"
Write-Host "  Release build:   cargo build --release"
Write-Host "  Binary:          .\target\release\discreet-server.exe"
Write-Host "===========================================================" -ForegroundColor Cyan
