#!/usr/bin/env bash
set -euo pipefail

# ═══════════════════════════════════════════════════════════
# Discreet — Local Development Setup (Linux / macOS)
# ═══════════════════════════════════════════════════════════

RED='\033[0;31m'
GREEN='\033[0;32m'
BOLD='\033[1m'
NC='\033[0m'

echo ""
echo -e "${BOLD}═══════════════════════════════════════════════════${NC}"
echo -e "${BOLD} Discreet — Local Development Setup${NC}"
echo -e "${BOLD}═══════════════════════════════════════════════════${NC}"
echo ""

# ── Step 1: Check prerequisites ──────────────────────────────────────────

check_cmd() {
  if ! command -v "$1" &>/dev/null; then
    echo -e "${RED}✗ $1 not found.${NC} $2"
    exit 1
  fi
  echo -e "${GREEN}✓${NC} $1"
}

echo -e "${BOLD}Step 1: Checking prerequisites${NC}"
check_cmd docker "Install: https://docs.docker.com/get-docker/"
check_cmd cargo "Install: https://rustup.rs"
check_cmd node "Install Node.js 20+: https://nodejs.org"
check_cmd git "Install: https://git-scm.com"
check_cmd openssl "Install: sudo apt install openssl"

NODE_MAJOR=$(node -v | sed 's/v//' | cut -d. -f1)
if [ "$NODE_MAJOR" -lt 20 ]; then
  echo -e "${RED}✗ Node.js $NODE_MAJOR found, need 20+${NC}"
  exit 1
fi
echo ""

# ── Step 2: Generate secrets ─────────────────────────────────────────────

echo -e "${BOLD}Step 2: Generating secrets${NC}"
DB_PASSWORD=$(openssl rand -hex 16)
REDIS_PASSWORD=$(openssl rand -hex 16)
JWT_SECRET=$(openssl rand -hex 64)
AGENT_KEY_SECRET=$(openssl rand -hex 32)
TOTP_KEY=$(openssl rand -hex 32)
echo -e "${GREEN}✓${NC} Secrets generated"
echo ""

# ── Step 3: Write .env ───────────────────────────────────────────────────

echo -e "${BOLD}Step 3: Writing .env${NC}"
cat > .env << EOF
# Generated by scripts/setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Local development — not for production use.

# ── Required ──
DATABASE_URL=postgres://discreet:${DB_PASSWORD}@localhost:5432/discreet
REDIS_URL=redis://:${REDIS_PASSWORD}@127.0.0.1:6379
JWT_SECRET=${JWT_SECRET}

# ── Encryption ──
TOTP_ENCRYPTION_KEY=${TOTP_KEY}
AGENT_KEY_SECRET=${AGENT_KEY_SECRET}

# ── Dev mode (skips production credential checks) ──
SELF_HOSTED=true

# ── CORS (Vite dev server + backend) ──
CORS_ORIGINS=http://localhost:5173,http://localhost:3000

# ── Server ──
HOST=0.0.0.0
PORT=3000
RUST_LOG=discreet_server=debug,tower_http=debug
EOF
echo -e "${GREEN}✓${NC} .env written"
echo ""

# ── Step 4: Write docker-compose.override.yml ────────────────────────────

echo -e "${BOLD}Step 4: Writing docker-compose.override.yml${NC}"
cat > docker-compose.override.yml << EOF
# Generated by scripts/setup.sh — contains credentials.
services:
  postgres:
    environment:
      POSTGRES_USER: discreet
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: discreet
  redis:
    command: redis-server --requirepass ${REDIS_PASSWORD}
EOF
echo -e "${GREEN}✓${NC} docker-compose.override.yml written"
echo ""

# ── Step 5: Set permissions ──────────────────────────────────────────────

echo -e "${BOLD}Step 5: Setting file permissions${NC}"
chmod 600 .env docker-compose.override.yml
echo -e "${GREEN}✓${NC} Permissions set (600)"
echo ""

# ── Step 6: Start Docker containers ──────────────────────────────────────

echo -e "${BOLD}Step 6: Starting PostgreSQL and Redis${NC}"
docker compose up -d
echo -e "${GREEN}✓${NC} Containers started"
echo ""

# ── Step 7: Wait for PostgreSQL ──────────────────────────────────────────

echo -e "${BOLD}Step 7: Waiting for PostgreSQL${NC}"
ATTEMPTS=0
until docker compose exec -T postgres pg_isready -U discreet -d discreet &>/dev/null; do
  ATTEMPTS=$((ATTEMPTS + 1))
  if [ $ATTEMPTS -ge 30 ]; then
    echo -e "${RED}✗ PostgreSQL not ready after 30s${NC}"
    exit 1
  fi
  sleep 1
  printf "."
done
echo ""
echo -e "${GREEN}✓${NC} PostgreSQL ready"
echo ""

# ── Step 8: Apply migrations ─────────────────────────────────────────────

echo -e "${BOLD}Step 8: Applying migrations${NC}"
for f in migrations/*.sql; do
  cat "$f" | docker compose exec -T postgres psql -U discreet -d discreet -q 2>/dev/null
done
echo -e "${GREEN}✓${NC} Migrations applied"
echo ""

# ── Step 9: Install frontend dependencies ────────────────────────────────

echo -e "${BOLD}Step 9: Installing frontend dependencies${NC}"
cd client && npm ci --silent && cd ..
echo -e "${GREEN}✓${NC} Frontend ready"
echo ""

# ── Step 10: Done ────────────────────────────────────────────────────────

echo ""
echo -e "${BOLD}═══════════════════════════════════════════════════${NC}"
echo -e "${GREEN} ✅ Setup complete!${NC}"
echo ""
echo "  Start backend:   cargo run"
echo "  Start frontend:  cd client && npm run dev"
echo "  Open browser:    http://localhost:5173"
echo ""
echo "  Health check:    http://localhost:3000/health"
echo "  Release build:   cargo build --release"
echo "  Binary:          ./target/release/discreet-server"
echo -e "${BOLD}═══════════════════════════════════════════════════${NC}"
