/*
 Generated by typeshare 1.x from discreet-kernel/src/
 DO NOT EDIT — regenerate with: npm run typeshare

 Source: ../discreet-kernel/src/error.rs
         ../discreet-kernel/src/types.rs
         ../discreet-kernel/src/render_model.rs
         ../discreet-kernel/src/permissions.rs
*/

// ─── error.rs ────────────────────────────────────────────────────────────────

export type KernelError =
  | { type: "NotInitialized" }
  | { type: "InvalidRequest"; content: string }
  | { type: "DecryptionFailed"; content: string }
  | { type: "EncryptionFailed"; content: string }
  | { type: "ValidationFailed"; field: string; message: string }
  | { type: "Unauthorized"; content: string }
  | { type: "Locked" }
  | { type: "InternalError"; content: string };

// ─── render_model.rs ─────────────────────────────────────────────────────────

export interface RenderMessage {
  id: string;
  content: SanitizedContent;
  capabilities: CapabilitySet;
  author: AuthorInfo;
  timestamp: number;
  edited: boolean;
  pinned?: string;
  thread_id?: string;
  reply_to?: string;
}

export interface SanitizedContent {
  text: string;
  formatting: FormattingSpan[];
  mentions: Mention[];
  code_blocks: CodeBlock[];
  links: ValidatedLink[];
}

export interface AuthorInfo {
  id: string;
  display_name: string;
  avatar_url?: string;
  tier: string;
  is_bot: boolean;
  badge?: string;
}

export interface ValidatedLink {
  url: string;
  display_text: string;
  is_internal: boolean;
  is_safe: boolean;
}

export interface FormattingSpan {
  start: number;
  end: number;
  style: FormattingStyle;
}

export type FormattingStyle =
  | "Bold"
  | "Italic"
  | "Code"
  | "Strikethrough"
  | "Spoiler";

export interface Mention {
  username: string;
  start: number;
  end: number;
}

export interface CodeBlock {
  content: string;
  language?: string;
  start: number;
  end: number;
  is_inline: boolean;
}

export interface AttachmentMeta {
  id: string;
  filename: string;
  content_type: string;
  size_bytes: number;
}

// ─── permissions.rs ──────────────────────────────────────────────────────────

export interface CapabilitySet {
  can_reply: boolean;
  can_edit: boolean;
  can_delete: boolean;
  can_forward: boolean;
  can_react: boolean;
  can_pin: boolean;
  can_report: boolean;
  can_start_thread: boolean;
  can_mention_everyone: boolean;
}

export interface PermissionSet {
  roles: string[];
  overrides: Record<string, boolean>;
}

// ─── types.rs ────────────────────────────────────────────────────────────────

export type KernelRequest =
  | { type: "Initialize" }
  | { type: "Encrypt"; channel_id: string; plaintext: string }
  | { type: "Decrypt"; channel_id: string; ciphertext: string }
  | { type: "ValidateInput"; field: string; value: string }
  | { type: "GetCapabilities"; channel_id: string; user_id: string; user_role: string }
  | { type: "ProcessIncoming"; payload: string }
  | { type: "GenerateOutgoing"; channel_id: string; text: string }
  | { type: "Unlock"; assertion: string }
  | { type: "PersistState" }
  | { type: "RestoreState"; encrypted_state: string };

export type KernelResponse =
  | { type: "Initialized" }
  | { type: "Encrypted"; ciphertext: string }
  | { type: "Decrypted"; render_model: RenderMessage }
  | { type: "ValidationResult"; valid: boolean; error?: string }
  | { type: "Capabilities"; caps: CapabilitySet }
  | { type: "IncomingProcessed"; render_models: RenderMessage[] }
  | { type: "OutgoingPayload"; encrypted: string }
  | { type: "Unlocked" }
  | { type: "StatePersisted"; sealed_state: string }
  | { type: "StateRestored" }
  | { type: "Error"; code: string; message: string };
